#!/bin/bash

PREVIEW_ACCEPT="application/vnd.github.antiope-preview+json"

have_curl() { test -x $(which curl) ; }
have_github_sha() { ! test -z "$GITHUB_SHA" ; }
have_github_action() { ! test -z "$GITHUB_ACTION" ; }
have_github_repository() { ! test -z "$GITHUB_REPOSITORY" ; }
action_sha() { have_github_sha && echo "$GITHUB_SHA" ; }
action_name() { have_github_action && echo "$GITHUB_ACTION" ; }
action_repository() { have_github_repository && echo "$GITHUB_REPOSITORY" ; }

current_run_id() {
	true \
		&& have_curl \
		&& have_github_sha \
		&& have_github_action \
		&& have_github_repository \
		&& curl -H "Accept: ${PREVIEW_ACCEPT}" \
			"https://api.github.com/repos/$(action_repository)/commits/$(action_sha)/check-runs" \
		| jq -r ".check_runs[] | select(.name == '$(action_name)') | .id" \
		|| { >&2 echo "something went wrong..." && exit 78 ; }
}

echo "Current Check Run ID: $(current_run_id)"
