name: Check, test, and build the code

on:
  push:
  schedule:
  - cron: 15 */6 * * *

jobs:
  check:
    name: Check and test the code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - name: Install the appropriate Rust toolchain
      run: |
        rustup toolchain install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Run rustfmt
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
    - name: Run clippy
      run: |
        rustup component add clippy
        cargo clippy --all-features -- -D clippy::all -W clippy::cargo -W clippy::pedantic
    - name: Run cargo check
      run: cargo check --all-features
    - name: Run cargo test
      run: cargo test --all-features

  test:
    name: Run tests and measure coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
    steps:
    - name: Install the appropriate Rust toolchain
      run: |
        rustup toolchain install ${{ matrix.rust }}
        rustup default ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
    - name: Cache target dir
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('target') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-
      continue-on-error: true
    - name: Generate and upload coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        env CARGO_TARGET_DIR=~/.cargo/target cargo install --force cargo-tarpaulin
        cargo tarpaulin --all-features --out Xml
        bash <(curl -s https://codecov.io/bash)
    - uses: actions/upload-artifact@master
      with:
        name: cobertura.xml
        path: cobertura.xml
